function getUnionInfo(ocid, date) {
  const params = { ocid };
  if (date) params.date = date;
  return fetch('/user/union', params);
}

function getUnionRaiderInfo(ocid, date) {
  const params = { ocid };
  if (date) params.date = date;
  return fetch('/user/union-raider', params);
}

function getUnionArtifactInfo(ocid, date) {
  const params = { ocid };
  if (date) params.date = date;
  return fetch('/user/union-artifact', params);
}

function testUnionFetch() {
  const ocid = "23bcc60a112813296978ecd5ac95f439efe8d04e6d233bd35cf2fabdeb93fb0d";
  const date = "2024-03-14"; // 선택적 매개변수

  console.log("Union Info:");
  console.log(getUnionInfo(ocid, date));
  /*
  { date: '2024-03-14T00:00+09:00',
    union_level: 8552,
    union_grade: '그랜드 마스터 유니온 2',
    union_artifact_level: 30,
    union_artifact_exp: 15,
    union_artifact_point: 10380 }
  */

  console.log("Union Raider Info:");
  console.log(getUnionRaiderInfo(ocid, date));
  /*
  Logging output too large. Truncating output. { date: '2024-03-14T00:00+09:00',
  union_raider_stat:
  [ '적 공격마다 70%의 확률로 순수 MP의 8% 회복',
    'DEX 80 증가',
    '최대 HP 5% 증가',
    '보스 몬스터 공격 시 데미지 5% 증가',
    '최대 MP 6% 증가',
    '최대 HP 2000 증가',
    'LUK 80 증가',
    'STR 100 증가',
    '스킬 재사용 대기시간 5% 감소',
    '메소 획득량 4% 증가',
    '크리티컬 확률 4% 증가',
    'INT 80 증가',
    '상태 이상 내성 4 증가',
    'STR 80 증가',
    'LUK 80 증가',
    '크리티컬 확률 4% 증가',
    'DEX 80 증가',
    '소환수 지속시간 10% 증가',
    'STR 80 증가',
    '공격 시 20%의 확률로 데미지 16% 증가',
    '버프 지속시간 20% 증가',
    'LUK 80 증가',
    'DEX 80 증가',
    'LUK 80 증가',
    'INT 80 증가',
    'STR, DEX, LUK 40 증가',
    '방어율 무시 5% 증가',
    '크리티컬 데미지 5% 증가',
    'DEX 80 증가',
    'STR 80 증가',
    'STR 80 증가',
    'DEX 80 증가',
    'INT 80 증가',
    'STR 80 증가',
    '최대 HP 2000 증가' ],
  union_occupied_stat:
  [ 'STR 25 증가',
    '크리티컬 데미지 20.00% 증가',
    '보스 몬스터 공격 시 데미지 40% 증가',
    '공격력 5 증가',
    'DEX 5 증가',
    '버프 지속시간 19% 증가',
    '방어율 무시 40% 증가' ],
  union_block:
  [ { block_type: '마법사',
      block_class: '에반',
      block_level: '200',
      block_control_point: [Object],
      block_position: [Object] },
    { block_type: '해적',
      block_class: '엔젤릭버스터',
      block_level: '200',
      block_control_point: [Object],
      block_position: [Object] },
    { block_type: '전사',
      block_class: '미하일',
      block_level: '200',
      block_control_point: [Object],
      block_position: [Object] },
    { block_type: '궁수',
      block_class: '메르세데스',
      block_level: '200',
      block_control_point: [Object],
      block_position: [Object] },
    { block_type: '도적',
      block_class: '팬텀',
      block_level: '200',
      block_control_point: [Object],
      block_position: [Object] },
    { block_type: '도적',
      block_class: '나이트로드',
      block_level: '200',
      block_control_point: [Object],
      block_position: [Object] },
    { block_type: '전사',
      block_class: '데몬어벤져',
      block_level: '200',
      block_control_point: [Object],
      block_position: [Object] },
    { block_type: '전사',
      block_class: '아델',
      block_level: '263',
      block_control_point: [Object],
      block_position: [Object] },
    { block_type: '마법사',
      block_class: '비숍',
      block_level: '200',
      block_control_point: [Object],
      block_position: [Object] },
    { block_type: '전사',
      block_class: '데몬슬레이어',
      block_level: '200',
      block_control_point: [Object],
      block_position: [Object] },
    { block_type: '해적',
      block_class: '바이퍼',
      block_level: '202',
      block_control_point: [Object],
      block_position: [Object] },
    { block_type: '도적',
      block_class: '호영',
      block_level: '210',
      block_control_point: [Object],
      block_position: [Object] },
    { block_type: '궁수',
      block_class: '신궁',
      block_level: '200',
      block_control_point: [Object],
      block_position: [Object] },
    { block_type: '궁수',
      block_class: '패스파인더',
      block_level: '200',
      block_control_point: [Object],
      block_position: [Object] },
    { block_type: '해적',
      block_class: '캡틴',
      block_level: '200',
      block_control_point: [Object],
      block_position: [Object] },
    { block_type: '전사',
      block_class: '카이저',
      block_level: '200',
      block_control_point: [Object],
      block_position: [Object] },
    { block_type: '궁수',
      block_class: '와일드헌터',
      block_level: '200',
      block_control_point: [Object],
      block_position: [Object] },
    { block_type: '해적',
      block_class: '메카닉',
      block_level: '200',
      block_control_point: [Object],
      block_position: [Object] },
    { block_type: '도적',
      block_class: '듀얼블레이더',
      block_level: '200',
      block_control_point: [Object],
      block_position: [Object] },
    { block_type: '궁수',
      block_class: '카인',
      block_level: '200',
      block_control_point: [Object],
      block_position: [Object] },
    { block_type: '도적',
      block_class: '섀도어',
      block_level: '200',
      block_control_point: [Object],
      block_position: [Object] },
    { block_type: '마법사',
      block_class: '루미너스',
      block_level: '200',
      block_control_point: [Object],
      block_position: [Object] },
    { block_type: '하이브리드',
      block_class: '제논',
      block_level: '200',
      block_control_point: [Object],
      block_position: [Object] },
    { block_type: '전사',
      block_class: '블래스터',
      block_level: '200',
      block_control_point: [Object],
      block_position: [Object] },
    { block_type: '해적',
      block_class: '은월',
      block_level: '200',
      block_control_point: [Object],
      block_position: [Object] },
    { block_type: '궁수',
      block_class: '보우마스터',
      block_level: '200',
      block_control_point: [Object],
      block_position: [Object] },
    { block_type: '해적',
      block_class: '바이퍼',
      block_level: '201',
      block_control_point: [Object],
      block_position: [Object] },
    { block_type: '전사',
      block_class: '팔라딘',
      block_level: '200',
      block_control_point: [Object],
      block_position: [Object] },
    { block_type: '전사',
      block_class: '히어로',
      block_level: '200',
      block_control_point: [Object],
      block_position: [Object] },
    { block_type: '마법사',
      block_class: '아크메이지(불,독)',
      block_level: '218',
      block_control_point: [Object],
      block_position: [Object] },
    { block_type: '도적',
      block_class: '카데나',
      block_level: '200',
      block_control_point: [Object],
      block_position: [Object] },
    { block_type: '궁수',
      block_class: '윈드브레이커',
      block_level: '200',
      block_control_point: [Object],
      block_position: [Object] },
    { block_type: '마법사',
      block_class: '키네시스',
      block_level: '200',
      block_control_point: [Object],
      block_position: [Object] },
    { block_type: '마법사',
      block_class: '아크메이지(불,독)',
      block_level: '251',
      block_control_point: [Object],
      block_position: [Object] },
    { block_type: '해적',
      block_class: '스트라이커',
      block_level: '200',
      block_control_point: [Object],
      block_position: [Object] },
    { block_type: '전사',
      block_class: '소울마스터',
      block_level: '200',
      block_control_point: [Object],
      block_position: [Object] },
    { block_type: '전사',
      block_class: '다크나이트',
      block_level: '200',
      block_control_point: [Object],
      block_position: [Object] } ],
  union_inner_stat:
  [ { stat_field_id: '0', stat_field_effect: '유니온 최대 MP' },
    { stat_field_id: '1', stat_field_effect: '유니온 LUK' },
    { stat_field_id: '2', stat_field_effect: '유니온 최대 HP' },
    { stat_field_id: '3', stat_field_effect: '유니온 공격력' },
    { stat_field_id: '4', stat_field_effect: '유니온 DEX' },
    { stat_field_id: '5', stat_field_effect: '유니온 STR' },
    { stat_field_id: '6', stat_field_effect: '유니온 마력' },
    { stat_field_id: '7', stat_field_effect: '유니온 INT' } ],
  use_preset_no: 2,
  union_raider_preset_1:
  { union_raider_stat:
      [ 'DEX 80 증가',
        '적 공격마다 70%의 확률로 순수 MP의 8% 회복',
        'LUK 80 증가',
        '적 공격마다 70%의 확률로 순수 HP의 8% 회복',
        '최대 MP 6% 증가',
        '최대 HP 2000 증가',
        '보스 몬스터 공격 시 데미지 5% 증가',
        '크리티컬 확률 4% 증가',
        '스킬 재사용 대기시간 5% 감소',
        '메소 획득량 4% 증가',
        'STR, DEX, LUK 40 증가',
        'LUK 80 증가',
        'STR 100 증가',
        'INT 80 증가',
        '공격력/마력 20 증가',
        '상태 이상 내성 4 증가',
        '크리티컬 확률 4% 증가',
        'LUK 80 증가',
        'DEX 80 증가',
        'INT 80 증가',
        '소환수 지속시간 10% 증가',
        'LUK 80 증가',
        'STR 80 증가',
        'INT 80 증가',
        'STR 80 증가',
        '버프 지속시간 20% 증가',
        '공격 시 20%의 확률로 데미지 16% 증가',
        'STR 80 증가',
        'STR 80 증가',
        'DEX 80 증가',
        '방어율 무시 5% 증가',
        '크리티컬 데미지 5% 증가',
        'LUK 80 증가',
        'INT 80 증가',
        'STR 80 증가',
        'STR 80 증가',
        'INT 80 증가' ],
  */

  console.log("Union Artifact Info:");
  console.log(getUnionArtifactInfo(ocid, date));
  /*
  { date: '2024-03-14T00:00+09:00',
      union_artifact_effect:
       [ { name: '올스탯 15 증가', level: 1 },
         { name: '최대 HP 750, 최대 MP 750 증가', level: 1 },
         { name: '공격력 15, 마력 15 증가', level: 5 },
         { name: '데미지 12.00% 증가', level: 8 },
         { name: '보스 몬스터 공격 시 데미지 12.00% 증가', level: 8 },
         { name: '몬스터 방어율 무시 16% 증가', level: 8 },
         { name: '버프 지속시간 8% 증가', level: 4 },
         { name: '재사용 대기시간 미적용 확률 3.00% 증가', level: 4 },
         { name: '크리티컬 확률 20% 증가', level: 10 },
         { name: '크리티컬 데미지 4.00% 증가', level: 10 },
         { name: '추가 경험치 획득 12% 증가, 다수 공격 스킬의 최대 공격 가능 대상 수 1 증가',
           level: 10 } ],
      union_artifact_crystal:
       [ { name: '크리스탈 : 주황버섯',
           validity_flag: '0',
           date_expire: '2024-03-22T18:27+09:00',
           level: 5,
           crystal_option_name_1: '크리티컬 확률 증가',
           crystal_option_name_2: '크리티컬 데미지 증가',
           crystal_option_name_3: '추가 경험치 획득 증가' },
         { name: '크리스탈 : 슬라임',
           validity_flag: '0',
           date_expire: '2024-03-22T18:27+09:00',
           level: 5,
           crystal_option_name_1: '크리티컬 확률 증가',
           crystal_option_name_2: '크리티컬 데미지 증가',
           crystal_option_name_3: '추가 경험치 획득 증가' },
         { name: '크리스탈 : 뿔버섯',
           validity_flag: '0',
           date_expire: '2024-03-22T18:27+09:00',
           level: 4,
           crystal_option_name_1: '데미지 증가',
           crystal_option_name_2: '보스 몬스터 공격 시 데미지 증가',
           crystal_option_name_3: '몬스터 방어율 무시 증가' },
         { name: '크리스탈 : 스텀프',
           validity_flag: '0',
           date_expire: '2024-03-22T18:27+09:00',
           level: 4,
           crystal_option_name_1: '데미지 증가',
           crystal_option_name_2: '보스 몬스터 공격 시 데미지 증가',
           crystal_option_name_3: '몬스터 방어율 무시 증가' },
         { name: '크리스탈 : 스톤골렘',
           validity_flag: '0',
           date_expire: '2024-03-22T18:27+09:00',
           level: 4,
           crystal_option_name_1: '버프 지속시간 증가',
           crystal_option_name_2: '재사용 대기시간 미적용 확률 증가',
           crystal_option_name_3: '공격력/마력 증가' },
         { name: '크리스탈 : 발록',
           validity_flag: '0',
           date_expire: '2024-04-13T17:59+09:00',
           level: 1,
           crystal_option_name_1: '올스탯 증가',
           crystal_option_name_2: '최대 HP/MP 증가',
           crystal_option_name_3: '공격력/마력 증가' } ],
      union_artifact_remain_ap: 5 }
  */
}
